Tried to adjust to CentOS 6, but failed at the python-build stage for as of yet unknown reasons:
E.p1 must be between 0.0 and 1.0
num_bits must be 64 or less
.
======================================================================
ERROR: testRandbits64 (__main__.FastRandTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fastrand_test.py", line 38, in testRandbits64
    self.assertLess(r, 2 ** n)
AttributeError: FastRandTest object has no attribute assertLess